import { useState } from 'react';
import { Plus, CalendarDays, Trash2, Check, Flag } from 'lucide-react';
import { dateKey, uid } from './model';
import type { CalendarEvent, Task } from './model';

export default function Tasks({ tasks, events, onChange, onSchedule }: { tasks: Task[]; events: CalendarEvent[]; onChange: (tasks: Task[]) => void; onSchedule: (task: Task) => void }) {
  const [filter, setFilter] = useState('active'), [title, setTitle] = useState(''), [due, setDue] = useState(''), [priority, setPriority] = useState<Task['priority']>('normal');
  const visible = tasks.filter(task => filter === 'all' || (filter === 'done' ? task.done : !task.done));
  const done = tasks.filter(task => task.done).length;
  return <section className="tasks-page page-width"><h1>待办</h1>
    <div className="task-summary"><span><b>{tasks.length - done}</b> 件待完成</span><span><b>{done}</b> 件已完成</span><div className="progress-track"><i style={{ width: `${tasks.length ? done / tasks.length * 100 : 0}%` }} /></div></div>
    <form className="task-add" onSubmit={event => { event.preventDefault(); if (!title.trim()) return; onChange([...tasks, { id: uid(), title: title.trim(), due, priority, done: false }]); setTitle(''); }}><Plus size={20} /><input aria-label="新待办" placeholder="添加一件想完成的事…" value={title} onChange={e => setTitle(e.target.value)} maxLength={160} required /><input aria-label="截止日期" type="date" value={due} onChange={e => setDue(e.target.value)} /><select aria-label="优先级" value={priority} onChange={e => setPriority(e.target.value as Task['priority'])}><option value="normal">普通</option><option value="high">优先</option></select><button className="primary">添加</button></form>
    <div className="task-filters">{[['active', '待完成'], ['done', '已完成'], ['all', '全部']].map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{label}</button>)}</div>
    <div className="task-list">{visible.map(task => { const scheduled = events.find(event => event.taskId === task.id); return <div className={`task-row ${task.done ? 'done' : ''}`} key={task.id}><button className="check-button" aria-label={`${task.done ? '恢复' : '完成'} ${task.title}`} onClick={() => onChange(tasks.map(item => item.id === task.id ? { ...item, done: !item.done } : item))}>{task.done && <Check size={15} />}</button><div className="task-content"><input aria-label="编辑待办名称" value={task.title} onChange={e => onChange(tasks.map(item => item.id === task.id ? { ...item, title: e.target.value } : item))} onBlur={() => { if (!task.title.trim()) onChange(tasks.map(item => item.id === task.id ? { ...item, title: '未命名待办' } : item)); }} /><small className={task.due && task.due < dateKey(new Date()) && !task.done ? 'overdue' : ''}>{task.due ? `截止 ${task.due}` : '没有截止日期'}{scheduled && ` · 已安排 ${dateKey(new Date(scheduled.start))}`}</small></div><button className={`icon-button ${task.priority === 'high' ? 'high-priority' : ''}`} aria-label="切换优先级" onClick={() => onChange(tasks.map(item => item.id === task.id ? { ...item, priority: item.priority === 'high' ? 'normal' : 'high' } : item))}><Flag size={17} /></button><button className="secondary schedule-button" disabled={task.done} onClick={() => onSchedule(task)}><CalendarDays size={15} />{scheduled ? '查看排期' : '安排时间'}</button><button className="icon-button" aria-label={`删除 ${task.title}`} onClick={() => onChange(tasks.filter(item => item.id !== task.id))}><Trash2 size={16} /></button></div>; })}</div>
    {!visible.length && <div className="large-empty"><Check size={32} /><h2>{filter === 'done' ? '暂无已完成待办' : '暂无待办'}</h2><p>{filter === 'done' ? '完成的待办会出现在这里。' : '在上方写下第一件待办。'}</p></div>}
  </section>;
}
